# **Using NumPy**

Once you've installed NumPy you can import it as a library:

In [45]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [46]:
arr = np.array(['1',2,3,4,5])
arr

array(['1', '2', '3', '4', '5'], dtype='<U21')

Lets create a matrix using list

In [47]:
a = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(a)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

Now lets see how matlix looks like using numpy arrays

In [48]:
arr = np.zeros([10,10])
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [49]:
arr = np.ones([5,7])
arr

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [50]:
arr =  np.full([5,5],7)
arr

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [51]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [53]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [57]:
np.random.rand(8,9)

array([[0.87969526, 0.21788935, 0.05923311, 0.88135653, 0.92911654,
        0.88583028, 0.76824973, 0.18319684, 0.41064538],
       [0.58825641, 0.66155041, 0.4966486 , 0.36621247, 0.67052757,
        0.93102041, 0.87625225, 0.15634222, 0.70944246],
       [0.17696705, 0.17172342, 0.04937192, 0.82474982, 0.75675995,
        0.88649394, 0.84783805, 0.69609029, 0.52293132],
       [0.8074953 , 0.85093718, 0.08624349, 0.02569125, 0.14439433,
        0.19116359, 0.14781913, 0.49197209, 0.00296758],
       [0.29781135, 0.88620347, 0.5214716 , 0.45535507, 0.74481432,
        0.08381476, 0.11836338, 0.395664  , 0.79144329],
       [0.91078349, 0.94339033, 0.4527891 , 0.26636756, 0.33458062,
        0.41991192, 0.95226902, 0.83916192, 0.95580701],
       [0.26153192, 0.8037012 , 0.72892846, 0.34525487, 0.7772012 ,
        0.01039297, 0.66723139, 0.74143982, 0.34265956],
       [0.5808911 , 0.24766629, 0.19368285, 0.33069359, 0.46287201,
        0.20807011, 0.53586915, 0.44598752, 0.42428496]])

In [59]:
np.random.randint(1,100,(3,4))

array([[76, 93, 33, 68],
       [90, 95,  2,  4],
       [33, 87, 74, 78]])

arange → step-based values

linspace → fixed number of values

eye → identity matrix

rand → random floats (0–1)

randint → random integers in a range

randn → random values from bell curve distribution